select * from customer

alter table customer rename column "Previous Purchases" to previous_purchases

--q1) what is the total revenue generated by male vs female
select gender,sum(purchase_amount)as revenue from customer group by gender
--q2) whis customer use discount but still spent more that avg. purchase amt.
select customer_id, purchase_amount
from customer 
where discount_applied='Yes' and
purchase_amount>=(select avg(purchase_amount) from customer)
--q3) which are the top 5 product with the higheest averge review rating?
select item_purchased,ROUND(avg(review_rating::numeric),2) as" Averge Product Rating"
from customer group by item_purchased order by avg(review_rating) desc
limit 5;
--q4) compare the average purchase amount between standard and express shipping
select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
group  by shipping_type
--q5) do subscribed customer spend more? compare average spend and total revenue between
--sbscribers abd non_subscribers
select subscription_status,
count(customer_id)as total_customer,
round(avg(purchase_amount),2)as avg_spent,
round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spent desc
--q6) which 5 product have the heighes percentages of purchases with discouts applied
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--q7) segment customer into new, returning and loyal based on their total 
--nmber fo previous purchases and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'new' 
when previous_purchases between 2 and 10 then 'returning'
else 'loyal' 
end as customer_segment 
from customer
)
select customer_segment, count(*) as "number of custoemrs"
from customer_type
group by customer_segment

--q8) what are the top 3 most purchased product within each catagory?
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) item_rank
from customer
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts

--q9) are customer who are reapeat byers (more than 5 previos purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status
--q10) what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount)as total_revenue
from customer 
group by age_group
order by total_revenue desc
